swagger: "3.0"
info:
  version: 1.0.0
  title: TRACK API Specification
  license:
    name: MIT
host: api.track.io
basePath: /v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /timers:
    get:
      summary: List all timers
      operationId: listTimers
      tags:
        - pets
      parameters:
        - name: date
          in: query
          description: The Date for the timers to return
          required: true
          type: string
          format: date
          example: 2020-08-09
      responses:
        "200":
          description: An array of timers
          schema:
            $ref: '#/definitions/Timers'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Timer:
    type: "object"
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        note:
          type: string
  Timers:
    type: array
    items:
      $ref: '#/definitions/Timer'
    example:
      - id: 1
        note: test
      - id: 2
        note: timer2
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
